DEFAULT_TODOS = [
    (
        "Learn Flask Update Feature",
        "Implemented update functionality in TODO app using Flask, SQLAlchemy, template inheritance, and SweetAlert notifications.",
    ),
    (
        "Built Complete Flask TODO Application",
        "Developed a full-stack TODO web application using Flask, SQLAlchemy, Bootstrap, Jinja template inheritance, JavaScript search functionality, and SweetAlert notifications with CRUD operations.",
    ),
    ("Complete Flask deployment setup", "Review requirements, Procfile, and runtime files before connecting the app to a hosting platform."),
    ("Create GitHub repository backup", "Confirm the latest project files are pushed to GitHub and the remote branch is tracking main."),
    ("Test homepage form submission", "Add a todo from the browser and verify it appears immediately in the table."),
    ("Check update page flow", "Open an existing todo, edit the title and description, then confirm the changes are saved."),
    ("Verify delete action", "Delete a sample todo and make sure the list refreshes without an error."),
    ("Clean project folders", "Remove temporary cache files and keep only source files needed for the Flask app."),
    ("Review database location", "Confirm the SQLite database is stored in the instance folder for local development."),
    ("Prepare Render deployment", "Use the render.yaml blueprint to create the hosted Flask web service."),
    ("Check application logs", "After deployment, read server logs for import errors, database errors, or missing dependency messages."),
    ("Update project README", "Write setup steps, local run instructions, and deployment notes for future reference."),
    ("Add form validation", "Prevent empty todo titles and descriptions from being saved to the database."),
    ("Improve delete safety", "Handle missing todo IDs gracefully so invalid delete links do not crash the app."),
    ("Style todo table for mobile", "Make the list easier to read on small screens by improving spacing and responsiveness."),
    ("Add created date formatting", "Display created_at values in a cleaner day, month, year, and time format."),
    ("Add search result reset", "Ensure highlighted search rows return to normal styling when the search box is cleared."),
    ("Create production checklist", "List the steps needed before sharing the deployed app link with other users."),
    ("Test app after restart", "Restart the Flask server and confirm the existing todos still load from the database."),
    ("Review Bootstrap CDN links", "Check that Bootstrap CSS and JavaScript load correctly in the browser."),
    ("Add favicon verification", "Confirm static/list.png loads as the browser tab icon without a missing file error."),
    ("Organize templates", "Keep base layout, index page, and update page consistent with shared blocks."),
    ("Check SQLAlchemy model names", "Review model naming and consider renaming TOdo to Todo for clarity later."),
    ("Add error page handling", "Create simple 404 and 500 pages so users see friendly messages on errors."),
    ("Document environment variables", "Explain how DATABASE_URL can be used when switching from SQLite to PostgreSQL."),
    ("Plan PostgreSQL migration", "Decide whether the hosted app should use SQLite disk storage or a managed database."),
    ("Run manual browser test", "Open the local app and test add, update, delete, and search from the UI."),
    ("Confirm Git ignore rules", "Make sure virtual environments, caches, and local database files are excluded from commits."),
    ("Create sample screenshots", "Capture screenshots of the todo list and update form for the GitHub README."),
    ("Review route names", "Check whether redirect and url_for should be used consistently across app routes."),
    ("Add flash messages", "Replace query string success handling with Flask flash messages for cleaner feedback."),
    ("Check timezone handling", "Verify new todo timestamps are saved using Asia/Kolkata time as expected."),
    ("Add unit tests for routes", "Create tests for homepage, add todo, update todo, and delete todo behavior."),
    ("Create deployment notes", "Record the exact steps used to deploy so the app can be redeployed later."),
    ("Review database backups", "Plan how to copy or export todo.db before making larger app changes."),
    ("Improve navbar search behavior", "Make search work only on pages where the todo table exists to avoid console errors."),
    ("Add confirmation before delete", "Show a confirmation prompt before permanently removing a todo item."),
    ("Improve empty list state", "Display a friendly message when there are no todos instead of showing an empty table."),
    ("Add priority field idea", "Plan a future priority column so important tasks can be sorted more easily."),
    ("Add due date idea", "Plan a future due date field for tasks that need deadlines."),
    ("Check HTML accessibility", "Review labels, button text, and table headings for clearer screen reader support."),
    ("Refactor comments later", "Keep useful comments but remove line-by-line explanations once the concepts are comfortable."),
    ("Create local setup guide", "Write commands for installing dependencies and running flask --app app run locally."),
    ("Confirm hosted static files", "After deployment, verify CSS, JavaScript, and image assets load on the live site."),
    ("Review commit history", "Check the latest Git commit message and confirm it describes the deployment setup."),
    ("Push latest database changes carefully", "Avoid committing the local SQLite database unless a sample database is intentionally needed."),
    ("Create issue list", "Turn planned improvements into GitHub issues so work can be tracked clearly."),
    ("Add pagination idea", "Plan pagination for the todo table if the database grows beyond a comfortable size."),
    ("Improve update button spacing", "Adjust action buttons so delete and update look neat on desktop and mobile."),
    ("Check browser console", "Open developer tools and confirm there are no JavaScript errors on the homepage."),
    ("Prepare final demo", "Create a clean set of todos and test the full app before showing it to others."),
    ("Share live project link", "After deployment is complete, copy the hosted URL and add it to the GitHub repository description."),
]
